name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew assembleRelease
  
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: ./app/build/outputs/apk/release/app-release-unsigned.apk
          if-no-files-found: error

      - name: Build version
        id: version
        run: |
          versionCode=$(grep -oP 'versionCode\s+\K\d+' ./app/build.gradle)
          echo "versionCode=$version_code" >> $GITHUB_ENV

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/release/app-release-unsigned.apk
          asset_name: JustTrustMe.apk
          tag: "${{env.versionCode}}"
          overwrite: true
